### ISSUE TITLE
Erroneous dependency creation for CommonPage

### ISSUE THREAD

**Issue by wridgeu** [ui5-community/ui5-journey-recorder#34]
Hey there,

love the extension!

I think there is a minor spelling mistake which leads to adding the wrong dependencies for the CommonPage file.

It should be matcher`s` instead, see: https://github.com/SAP/openui5/tree/master/src/sap.ui.core/src/sap/ui/test/matchers / https://ui5.sap.com/#/entity/sap.ui.test.matchers

Here: 
https://github.com/ui5-community/ui5-journey-recorder/blob/781f204a1b37c72ee3d3a65f7afa69ffc242c6bc/app/src/app/scenario/codeService/strategies/opa5/CommonPageBuilder.ts#L215-L234

BR,
Marco

**Comment by tabris87** [comment]
Yeah, right the "s" is missing. 
Will fix this as soon as possible.
