### ISSUE TITLE
Unknown StepType for input type fields

### ISSUE THREAD

**Issue by prashant4be** [ui5-community/ui5-journey-recorder#71]
Observe that getting error as unknown StepType for Input fields when I tried to record journey using Recorder,

I tried for standard demo app Browse Order app https://sapui5.hana.ondemand.com/test-resources/sap/m/demokit/orderbrowser/webapp/test/mockServer.html?sap-ui-theme=sap_horizon#

Tried to Search field to input some text but unfortunately not recorded correctly by Recorder, is that version issue?
As I checked couple of videos in that it seems for input enterText("") correctly recorded but for me it didn't worked,
Reference video https://youtu.be/oJCcFkwYyYM?t=675

Is there I missed something? @tabris87 

<img width="912" alt="image" src="https://github.com/ui5-community/ui5-journey-recorder/assets/130567968/0957f784-0456-4635-9080-58ab4a6058f5">

**Comment by tabris87** [comment]
So currently i don't see an issue within your usage.
As the generated code looks not clean as well. 

I will check with the provided app.

**Comment by tabris87** [comment]
@prashant4be: I fixed the intended behaviour of the JourneyRecorder.  The Click/Validation Step followed by consecutive KeyPress Steps should be converted into one InputStep. 
This also leads to the correct test code

Hopefully this release is published soon by Google

**Comment by prashant4be** [comment]
Thank you for the update.
